red-data-tools/red-datasets

- .travis.yml
This pull request bumps Ruby versions at Travis to its latest teeny versions.
* [Ruby 2.3.7 Released](https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-3-7-released/)
* [Ruby 2.4.4 Released](https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-4-4-released/)
* [Ruby 2.5.1 Released](https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-5-1-released/)
> Bump Ruby versions at Travis to its latest teeny versions

- lib/datasets/adult.rb
This pull request suppresses Ruby 2.7 warnings below.
```ruby
% ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
% rake test
/Users/yahonda/.rbenv/versions/2.7.0/bin/ruby test/run-test.rb
Loaded suite test
Started
./Users/yahonda/src/github.com/yahonda/red-datasets/lib/datasets/adult.rb:65: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/yahonda/.rbenv/versions/2.7.0/lib/ruby/2.7.0/csv.rb:635: warning: The called method `open' is defined here
```
> Suppress Ruby 2.7 warnings

- .travis.yml
* Support of Ruby 2.3 has ended
https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/
> Drop CI against Ruby 2.3 which already EOLed

- lib/datasets/seaborn-data.rb
- test/test-seaborn-data.rb
(This is a splitted feature in #132)
`SeabornData` consists of 19 datasets but there is no dataset list now.
This PR is to introduce `SeabornDataList` class containing a list of datasets available.
Unfortunately data source has no `.csv` for summary, so the list is acquired from `.html` of data source directory.
This is a same way as original seaborn library is doing in `get_dataset_names()` method.
> Add ::SeabornDataList

- lib/datasets/ita-corpus.rb
My dear rubocop says that this private access modifier makes no difference because there is already another private modifier.
> Removed needless line

- lib/datasets/postal-code-japan.rb
zip download url has changed in Postal code japan - romaji.
https://www.post.japanpost.jp/zipcode/dl/roman-zip.html
> postal_code_japan: Fix zip url of romaji

- lib/datasets/rdatasets.rb
- test/test-rdatasets.rb
This pull request is a solution about #138 .
- First, introduce CSV#table to access by column later.
This change is faster than before change.
```
$ bundle exec benchmark-driver benchmark_rdataset.yml
(snipped)
original     21.516 i/s -      65.000 times in 3.021053s (46.48ms/i)
new code     28.640 i/s -      90.000 times in 3.142489s (34.92ms/i)
```
benchmark_rdataset.yml
```
prelude: |
require 'datasets'
dataset = Datasets::Rdatasets.new('datasets', 'quakes')
benchmark:
'new code': 'dataset.to_a'
```
> Fix Rdatasets#each to change "NA" to nil

- Gemfile.lock
- lib/datasets/postal-code-japan.rb
- test/test-rdatasets.rb
- test/test-seaborn.rb
- test/test-sudachi-synonym-dictionary.rb
Now the test has 3 Failures and 1 Error.
This request will fix them.
This reverts commit 7aeefd82c899afb69eb7494c7ac42905338f6170 (#141).
Source data has reverted to previous zip file name.
https://www.post.japanpost.jp/zipcode/dl/roman-zip.html
> Fix errors in test

- test/test-cldr-plurals.rb
- test/test-geolonia.rb
- test/test-rdataset.rb
Rationale for this change
---
Following tests are fail because available datasets have been updated.
- CLDR language plural rules
- Geolonia
- Rdataset
What changes are included in this PR?
---
Update expected. But postal code japan of test is still error. It fixes 4b1d568 on next PR.
> test cldr, geolonia, rdataset: update expected

- lib/datasets/postal-code-japan.rb
Rationale for this change
---
Unable to download `ken_all_rome.zip` for the test of postal code in
Japan because the downloaded URL is `ken_all_rome.zip`, not
`KEN_ALL_ROME.zip`. It has been modified below.
https://www.post.japanpost.jp/zipcode/dl/roman-zip.html
What changes are included
---
Modify the downloaded URL.
> test postal code japan: modify the downloaded URL

- lib/datasets/quora-duplicate-question-pair.rb
Because date_time and float are not included in tsv.
```bash
$ time ruby -I lib test/run-test.rb -t "/QuoraDuplicateQuestionPairTest/" -v
Loaded suite test
Started
QuoraDuplicateQuestionPairTest:
test: #each:                                                                                                                  .: (24.666772)
Finished in 24.667106 seconds.
-------------------------------------------------------------------------------------------------------------------------------------------------
1 tests, 1 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-------------------------------------------------------------------------------------------------------------------------------------------------
0.04 tests/s, 0.04 …
```
> quora: reduce needless converters

- test/test-quora-duplicate-question-pair.rb
Because tsv file is too big(404,290 rows).
```bash
$ time ruby -I lib test/run-test.rb -t "/QuoraDuplicateQuestionPairTest/" -v
Loaded suite test
Started
QuoraDuplicateQuestionPairTest:
test: #each:                                                         .: (17.476536)
Finished in 17.476912 seconds.
-------------------------------------------------------------------------------------
1 tests, 1 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-------------------------------------------------------------------------------------
0.06 tests/s, 0.06 assertions/s
real    0m18.117s
user    0m17.554s
sys     0m0.383s
```
```bash
$ time ruby -I lib test/run-test.rb -t "/QuoraDuplicateQuestionPairTest/" -v
Loaded suite …
```
> test quora: reduce checking

- lib/datasets/dataset.rb
- lib/datasets/downloader.rb
- lib/datasets/fashion-mnist.rb
- lib/datasets/kuzushiji-mnist.rb
- lib/datasets/mnist.rb
- test/test-downloader.rb
MNIST's original server is sometimes refusing to provide the requested
resource. So, we use the mirror server only when the original server is
refusing it.
Moreover this includes the following changes.
- Support fallback in Downloader
Fixes GH-195.
> mnist: use mirror only when original server is not available

- lib/datasets/wikipedia-kyoto-japanese-english.rb
Using `Datasets::WikipediaKyotoJapaneseEnglish#each` raised an `entity expansion has grown too large (RuntimeError)`. This error occurs because the entity expansion limit in REXML is set by https://github.com/ruby/rexml/pull/187, and `Datasets::WikipediaKyotoJapaneseEnglish#each` exceeds that limit.
In Red Datasets, increasing the entity expansion limit is not a problem because we want to handle large datasets.
Therefore, we temporarily increase the limit.
```console
$ cd red-datasets && bundle
$ bundle exec ruby example/wikipedia-kyoto-japanese-english.rb
...
/home/otegami/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/rexml-3.3.4/lib/rexml/parsers/baseparser.rb:560:in `block in unnormalize': entity expansion has grown too large (RuntimeError)
...
```
> wikipedia-kyoto-japanese-english: increase REXML entity expansion limit during XML parsing

- lib/datasets/wikipedia-kyoto-japanese-english.rb
This reverts commit a76b9176f88ce3248e5f97867088bec29ed521cc.
REXML has fixed the bug where `REXML::Security.entity_expansion_text_limit` incorrectly calculated text size in both SAX and pull parsers. Therefore, we no longer need to handle this issue within Red Datasets.
ref: https://github.com/ruby/rexml/releases/tag/v3.3.5
> Revert "wikipedia-kyoto-japanese-english: increase REXML entity expansion limit during XML parsing (#198)

- test/test-geolonia.rb
GitHub: GH-188
Because csv file is too big (277,656 rows).
```console
$ time ruby test/run-test.rb -t GeoloniaTest --verbose=important-only
Finished in 5.998956 seconds.
notifications
real    0m6.603s
user    0m6.146s
sys     0m0.346s
```
```console
$ time ruby test/run-test.rb -t GeoloniaTest --verbose=important-only
Finished in 0.001634 seconds.
notifications
real    0m0.564s
user    0m0.388s
sys     0m0.087s
```
> test geolonia: reduce checking

- lib/datasets/ggplot2-dataset.rb
GitHub: GH-188
Because date_time is not included in the following csvs.
* diamonds.csv (diamonds dataset inherits from `Ggplot2Dataset`)
* mpg.csv (fuel economy dataset inherits from `Ggplot2Dataset`)
```console
$ time ruby test/run-test.rb -t DiamondsTest --verbose=important-only
Finished in 3.702616 seconds.
notifications
real    0m4.665s
user    0m4.136s
sys     0m0.226s
```
```console
$ time ruby test/run-test.rb -t DiamondsTest --verbose=important-only
Finished in 3.367821 seconds.
notifications
real    0m4.179s
user    0m3.738s
sys     0m0.202s
```
After this change, the fuel economy dataset test also …
> test diamonds: reduce needless converters

- test/test-diamonds.rb
GitHub: GH-188
Because csv file is too big (53,940 rows).
```console
$ time ruby test/run-test.rb -t DiamondsTest --verbose=important-only
Finished in 3.367821 seconds.
notifications
real    0m4.179s
user    0m3.738s
sys     0m0.202s
```
```console
$ time ruby test/run-test.rb -t DiamondsTest --verbose=important-only
Finished in 0.002048 seconds.
notifications
real    0m0.551s
user    0m0.379s
sys     0m0.085s
```
> test diamonds: reduce checking

- lib/datasets/california-housing.rb
Before change:
```console
$ ruby test/run-test.rb -t CaliforniaHousingTest 2>&1 | grep red-datasets
/Users/zzz/src/github.com/red-data-tools/red-datasets/lib/datasets/california-housing.rb:42:
warning: literal string will be frozen in the future
```
After change:
```console
$ ruby test/run-test.rb -t CaliforniaHousingTest 2>&1 | grep red-datasets
```
> california-housing: suppress "literal string will be frozen in the future" warning

- lib/datasets/ggplot2-dataset.rb
Before change:
```console
$ ruby test/run-test.rb -t '/DiamondsTest|FuelEconomyTest/' 2>&1 | grep red-datasets
/Users/zzz/src/github.com/red-data-tools/red-datasets/lib/datasets/ggplot2-dataset.rb:49: warning: literal string will be frozen in the future
(repeated 29 times)
```
After change:
```console
$ ruby test/run-test.rb -t '/DiamondsTest|FuelEconomyTest/' 2>&1 | grep red-datasets
```
> diamonds, fuel-economy: suppress "literal string will be frozen in the future" warning

- test/test-adult.rb
GitHub: GH-188
Because csv file is too big (32,561 rows).
```console
$ time ruby test/run-test.rb -t AdultTest::train --verbose=important-only
Finished in 2.742848 seconds.
1 tests, 1 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0
notifications
real    0m3.366s
user    0m3.064s
sys     0m0.183s
```
```console
$ time ruby test/run-test.rb -t AdultTest::train --verbose=important-only
Finished in 0.001817 seconds.
1 tests, 1 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0
notifications
real    0m0.587s
user    0m0.395s
sys     0m0.093s
```
> test adult-train: reduce checking

- test/test-house-of-councillor.rb
Because verify "literal string will be frozen in the future" warning.
> test house-of-councillor: add a test for invalid type

- lib/datasets/house-of-councillor.rb
Before change:
```console
$ ruby test/run-test.rb -t HouseOfCouncillorTest 2>&1 | grep red-datasets
/Users/zzz/src/github.com/red-data-tools/red-datasets/lib/datasets/house-of-councillor.rb:108: warning: literal string will be frozen in the future
/Users/zzz/src/github.com/red-data-tools/red-datasets/lib/datasets/house-of-councillor.rb:149: warning: literal string will be frozen in the future
/Users/zzz/src/github.com/red-data-tools/red-datasets/lib/datasets/house-of-councillor.rb:151: warning: literal string will be frozen in the future
/Users/zzz/src/github.com/red-data-tools/red-datasets/lib/datasets/house-of-councillor.rb:153: warning: literal string will be frozen in the future
/Users/zzz/src/github.com/red-data-tools/red-datasets/lib/datasets/house-of-councillor.rb:155: warning: …
```
> house-of-councillor: suppress "literal string will be frozen in the future" warning

- lib/datasets/nagoya-university-conversation-corpus.rb
Before change:
```console
$ git grep --ignore-case curpus
lib/datasets/nagoya-university-conversation-corpus.rb:      @metadata.id = 'nagoya-university-conversation-curpus'
lib/datasets/nagoya-university-conversation-corpus.rb: @metadata.name = 'Nagoya University Conversation Curpus'
```
After change:
```console
$ git grep --ignore-case curpus
```
> nagoya-university-conversation-corpus: fix typo

- lib/datasets/japanese-date-parser.rb
Before change:
```console
$ ruby test/run-test.rb -t JapaneseDateParserTest 2>&1 | grep red-datasets
/Users/zzz/src/github.com/red-data-tools/red-datasets/lib/datasets/japanese-date-parser.rb:19: warning: literal string will be frozen in the future
```
After change:
```console
$ ruby test/run-test.rb -t JapaneseDateParserTest 2>&1 | grep red-datasets
```
> japanese-date-parser: suppress "literal string will be frozen in the future" warning

- test/test-nagoya-university-conversation-corpus.rb
GitHub: GH-188
Because text file is too big (134,555 rows in total).
```console
$ time ruby test/run-test.rb -t NagoyaUniversityConversationCorpusTest --verbose=important-only
Finished in 3.65658 seconds.
4 tests, 4 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0
notifications
real    0m4.550s
user    0m3.723s
sys     0m0.568s
```
```console
$ time ruby test/run-test.rb -t NagoyaUniversityConversationCorpusTest --verbose=important-only
Finished in 0.060458 seconds.
4 tests, 4 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0
notifications
real    0m0.613s
user    0m0.428s
sys     0m0.096s
```
> test nagoya-university-conversation-corpus: reduce checking

- .github/workflows/test.yml
Because Ruby 3.0 reached EOL on 2024-04-23.
See also:
https://www.ruby-lang.org/en/news/2024/04/23/ruby-3-0-7-released/
> ci: remove EOL-ed Ruby

- lib/datasets/libsvm-dataset-list.rb
Before change:
```console
$ ruby test/run-test.rb -t LIBSVMDatasetListTest 2>&1 | grep red-datasets
/Users/zzz/src/github.com/red-data-tools/red-datasets/lib/datasets/libsvm-dataset-list.rb:136: warning: literal string will be frozen in the future
(repeated 7 times)
```
After change:
```console
$ ruby test/run-test.rb -t LIBSVMDatasetListTest 2>&1 | grep red-datasets
```
> libsvm-dataset-list: suppress "literal string will be frozen in the future" warning

- test/test-california-housing.rb
GitHub: GH-188
Because csv file is too big (20,640 rows).
```console
$ time ruby test/run-test.rb -t CaliforniaHousingTest --verbose=important-only
Finished in 1.453959 seconds.
notifications
real    0m3.029s
user    0m1.745s
sys     0m0.161s
```
```console
$ time ruby test/run-test.rb -t CaliforniaHousingTest --verbose=important-only
Finished in 0.331599 seconds.
notifications
real    0m1.126s
user    0m0.738s
sys     0m0.143s
```
> test california-housing: reduce checking

- test/test-postal-code-japan.rb
Because verify "literal string will be frozen in the future" warning.
> test postal-code-japan: add a test for invalid reading

- test/test-sudachi-synonym-dictionary.rb
GitHub: GH-188
Because csv file is too big (67,753 rows).
```console
$ time ruby test/run-test.rb -t SudachiSynonymDictionaryTest --verbose=important-only
Finished in 1.296801 seconds.
notifications
real    0m1.964s
user    0m1.740s
sys     0m0.118s
```
```console
$ time ruby test/run-test.rb -t SudachiSynonymDictionaryTest --verbose=important-only
Finished in 0.010658 seconds.
notifications
real    0m0.634s
user    0m0.455s
sys     0m0.092s
```
> test sudachi-synonym-dictionary: reduce checking

- lib/datasets/postal-code-japan.rb
Before change:
```console
$ ruby test/run-test.rb -t PostalCodeJapanTest 2>&1 | grep red-datasets
/Users/zzz/src/github.com/red-data-tools/red-datasets/lib/datasets/postal-code-japan.rb:45: warning: literal string will be frozen in the future
```
After change:
```console
$ ruby test/run-test.rb -t PostalCodeJapanTest 2>&1 | grep red-datasets
```
> postal-code-japan: suppress "literal string will be frozen in the future" warning

- test/test-adult.rb
GitHub: GH-188
Because csv file is too big (16,281 rows).
```console
$ time ruby test/run-test.rb -t AdultTest::test --verbose=important-only
Finished in 1.355024 seconds.
1 tests, 1 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0
notifications
real    0m1.980s
user    0m1.777s
sys     0m0.113s
```
```console
$ time ruby test/run-test.rb -t AdultTest::test --verbose=important-only
Finished in 0.002213 seconds.
1 tests, 1 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0
notifications
real    0m0.619s
user    0m0.442s
sys     0m0.089s
```
> test adult-test: reduce checking

- Gemfile
- Steepfile
- red-datasets.gemspec
To introduce rbs to this repository, I added the necessary gems like `steep` and `typeprof` to gemspec file.
I use these two gems to get support for the RBS file's type checking and type generation. 
I also added a Steepfile, which includes how to check the RBS files. The configuration of Steepfile is minimal, such as which directory to put RBS files in and not to raise an error with type checking at first.
This is a PR for preparation to introduce RBS to this repository, I added only configuration files.
The actual RBS file will be added in the next PR with a new dataset.
> Prepare to introduce rbs and add a configuration file

- lib/datasets/downloader.rb
GitHub: fix GH-242
Red Datasets sometimes handle large files. Downloading the same data multiple times is not suitable for this use case. We should not download per worker.
Add a cache check not only before acquiring the lock, but also after acquiring the lock.
While checking only after acquiring the lock would be enough, it would create a lock file unnecessarily, so we kept the pre-lock cache check as well.
This patch will avoid duplicate downloads in the following case:
```mermaid
sequenceDiagram
participant P1 as Process 1
participant P2 as Process 2
participant FS as File System
P1->>FS: check output_path.exist? => false
P2->>FS: check output_path.exist? => false
P1->>FS: create lock => success
P2->>FS: create lock => failure (sleep 1~10s)
P1->>FS: download
P1->>FS: delete lock …
```
> downloader: avoid duplicate downloads

- lib/datasets/downloader.rb
Correct the elapsed time comparison for lock file validation. Lock files should be considered valid when they are recent (< 10 seconds), not when they are old (> 10 seconds).
- Before: Lock files older than 10 seconds were considered valid
- After: Lock files newer than 10 seconds are considered valid
Originally suggested in a Copilot [review](https://github.com/red-data-tools/red-remote-input/pull/10#discussion_r2277833186)
> Fix lock validation logic in downloader synchronization
